/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_gslab_ibored_MainActivity */

#ifndef _Included_com_example_gslab_ibored_MainActivity
#define _Included_com_example_gslab_ibored_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_gslab_ibored_MainActivity
 * Method:    UpdateResult
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_gslab_ibored_MainActivity_UpdateResult
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
